name: ecommerce_app
description: A simple Flutter e‑commerce demo with navigation and routing.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  intl: ^0.19.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Use these specific, stable versions
  mockito: 5.4.5
  build_runner: 2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

# This override is our final, unbreakable rule for the analyzer.
dependency_overrides:
  analyzer: '6.2.0'